[package]
name = "ipm"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
env_logger = "0.11.8"
ipak = { path = "lib/ipak" }
log = "0.4.27"
